// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class IslamicFinanceTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void islamicFinance() {
    driver.get("https://advance-lexis-com.proxy.library.cornell.edu/firsttime?crid=6f39c92a-55e9-4c90-96ae-fff60e8a840b");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("searchTerms")).click();
    driver.findElement(By.id("searchTerms")).sendKeys("Islamic F");
    driver.findElement(By.id("searchTerms")).sendKeys("Islamic Fina");
    driver.findElement(By.id("searchTerms")).sendKeys("Islamic Finance");
    driver.findElement(By.cssSelector(".links:nth-child(1)")).click();
    driver.findElement(By.id("mainSearch")).click();
    driver.findElement(By.cssSelector(".row_sr0 .doc-title")).click();
    driver.findElement(By.cssSelector(".checkbox")).click();
    driver.findElement(By.cssSelector(".hideInMobile > input")).click();
    driver.findElement(By.cssSelector(".has_tooltip:nth-child(1) > .la-Download")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".button-group > .primary")).click();
    vars.put("win8483", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win8483").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.cssSelector(".row_sr0 .row-content")).click();
    js.executeScript("window.scrollTo(0,2667)");
    driver.findElement(By.linkText("2")).click();
    js.executeScript("window.scrollTo(0,0)");
    {
      WebElement element = driver.findElement(By.cssSelector(".hideInMobile > input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".hideInMobile > input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".hideInMobile > input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".hideInMobile > input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".hideInMobile > input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".hideInMobile > input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".hideInMobile > input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".hideInMobile > input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".has_tooltip:nth-child(1) > .la-Download"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".has_tooltip:nth-child(1) > .la-Download"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".has_tooltip:nth-child(1) > .la-Download"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".has_tooltip:nth-child(1) > .la-Download")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".button-group > .primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".button-group > .primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".button-group > .primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".button-group > .primary")).click();
    vars.put("win1443", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1443").toString());
  }
}
