# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestIslamicFinance():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_islamicFinance(self):
    self.driver.get("https://advance-lexis-com.proxy.library.cornell.edu/firsttime?crid=6f39c92a-55e9-4c90-96ae-fff60e8a840b")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.ID, "searchTerms").click()
    self.driver.find_element(By.ID, "searchTerms").send_keys("Islamic F")
    self.driver.find_element(By.ID, "searchTerms").send_keys("Islamic Fina")
    self.driver.find_element(By.ID, "searchTerms").send_keys("Islamic Finance")
    self.driver.find_element(By.CSS_SELECTOR, ".links:nth-child(1)").click()
    self.driver.find_element(By.ID, "mainSearch").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row_sr0 .doc-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hideInMobile > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has_tooltip:nth-child(1) > .la-Download").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".button-group > .primary").click()
    self.vars["win8483"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win8483"])
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".row_sr0 .row-content").click()
    self.driver.execute_script("window.scrollTo(0,2667)")
    self.driver.find_element(By.LINK_TEXT, "2").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".hideInMobile > input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".hideInMobile > input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".hideInMobile > input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".hideInMobile > input").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".hideInMobile > input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".hideInMobile > input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".hideInMobile > input")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".hideInMobile > input").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".has_tooltip:nth-child(1) > .la-Download")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".has_tooltip:nth-child(1) > .la-Download")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".has_tooltip:nth-child(1) > .la-Download")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".has_tooltip:nth-child(1) > .la-Download").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".button-group > .primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".button-group > .primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".button-group > .primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".button-group > .primary").click()
    self.vars["win1443"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win1443"])
  
